### ISSUE TITLE
能加个微信吗？

### ISSUE THREAD

**Issue by tonyqus** [LittleLittleCloud/Torchsharp-llama#1]
你好，我看你在贡献https://github.com/dotnet/csharp-notebooks

![image](https://github.com/LittleLittleCloud/Torchsharp-llama/assets/772561/29f997d8-8e0f-4f40-8ce5-44d58897397c)

我最近也有一些想法想维护一个中文版的C#教程，想交流下。

**Comment by tonyqus** [comment]
我找到你领英了，已加，等通过。

**Comment by LittleLittleCloud** [comment]
噢你好，才看到你的issue
